# Generated by Django 4.0.5 on 2022-07-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='caps')),
                ('desc', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
