# Generated by Django 4.0.5 on 2022-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='qty_sold',
            field=models.IntegerField(default=0),
        ),
    ]
