# Generated by Django 4.0.5 on 2022-07-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0002_cap_qty_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
